#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Kwan Wai-Pang"
# Short bio or description (displayed in the header)
description: "Personal Blog"

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: # https://avatars.githubusercontent.com/u/44108932?s=400&u=dbbb2abcd70a8baf00fe0ec6e6563e223cb58a0d&v=4
# avatar 不输入则不会显示头像图片

# 访客地球仪（MapMyVisitors globe.js 地址）
visitor_globe: //mapmyvisitors.com/globe.js?d=qAAbVjlo9WWMB5wmuf9D9eWuQQR6RJ_v_zyIbWldNR4

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://kwanwaipang.github.io/Poster_files/hku_logo.jpg

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Home
    url: /home
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags
  - name: About
    url: /about #/ #https://kwanwaipang.github.io/ 

# Pagination（分页）
paginate: 10 #8 

excerpt_separator: <!-- more -->

# Includes an icon in the footer for each username you enter（配置各种社交链接，请见_includes\svg-icons.html）
footer-links:
  home: https://kwanwaipang.github.io/  #https://kwanwaipang.github.io/File/Blogs/My_Blog.html
  email: wpguan@connect.hku.hk
  google_scholar: "fUU5Cv0AAAAJ"
  ORCID: # "0000-0003-4518-7852"
  Clarivate: # "AAV-2613-2020"
  Scopus_id: # "56957694200"
  ResearchGate: # "Guan-Wp"
  github: KwanWaiPang 
  youtube: "@Kwan-WaiPang"
  bilibili: "499377825"  # B 站 ID

# Text under the icons in footer
footer-text: A simple star should be the best affirmation 😊
# Please contact me for authorization before reusing or reposting

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # fromendworld

# Gitalk（评论功能的配置）
gitalk:
  clientID: Ov23liD7RVncxyVJkpxC
  clientSecret: 8ce63fcbaa301ab0fb7f54e4c7d69d2f17ab1fc3
  repo: KwanWaiPang.github.io
  owner: kwanwaipang

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-R1QX9D95NS

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://kwanwaipang.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "" # 若非子目录，留空


# Jekyll 默认使用 kramdown 作为 Markdown 解析器，需确保启用数学公式支持：
markdown: kramdown
# kramdown:
#   math_engine: mathjax  # 指定使用MathJax处理数学公式
#   syntax_highlighter: rouge

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: "/home/page:num/" #/page:num/ #指定分页页面的目标路径(若博客主页不在根目录下，需修改)

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  math_engine: mathjax  # 指定使用MathJax处理数学公式
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

